import sys
print('name','lines','spaces','words','length','tabs',' braces',' brackets','classs',' javascript','meta_content',' input',' forum',' gif',' js','css',' adblockkey','fb',' gmail',' twitter','linkedIn','subscribe','href','http',' bracket_2',' bracket_3','re_w','new_par',' dbslash',' bslash','bol_0','bol_1','bol_2','bol_3','bol_4','bol_5','bol_6','bol_7','bol_8','bol_9','bol_10','bol_11','bol_12','bol_13','bol_14','bol_15','bol_16','bol_17','bol_18','bol_19')
(Last__name,Last__lines,Last_spaces,Last_words,Last_length,Last_tabs, Last_braces, Last_brackets,Last_classs, Last_javascript,Last_meta_content, Last_input, Last_forum, Last_gif, Last_js,Last_css, Last_adblockkey,Last_fb, Last_gmail, Last_twitter,Last_linkedIn,Last_subscribe,Last_href,Last_http, Last_bracket_2, Last_bracket_3,Last_re_w,Last_new_par, Last_dbslash, Last_bslash,Last_bol_0,Last_bol_1,Last_bol_2,Last_bol_3,Last_bol_4,Last_bol_5,Last_bol_6,Last_bol_7,Last_bol_8,Last_bol_9,Last_bol_10,Last_bol_11,Last_bol_12,Last_bol_13,Last_bol_14,Last_bol_15,Last_bol_16,Last_bol_17,Last_bol_18,Last_bol_19) = (None,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0)
for line in sys.stdin:
	(name,lines,spaces,words,length,tabs, braces, brackets,classs, javascript,meta_content, input, forum, gif, js,css, adblockkey,fb, gmail, twitter,linkedIn,subscribe,href,http, bracket_2, bracket_3,re_w,new_par, dbslash, bslash,bol_0,bol_1,bol_2,bol_3,bol_4,bol_5,bol_6,bol_7,bol_8,bol_9,bol_10,bol_11,bol_12,bol_13,bol_14,bol_15,bol_16,bol_17,bol_18,bol_19)= line.strip().split(",")
	(name,lines,spaces,words,length,tabs, braces, brackets,classs, javascript,meta_content, input, forum, gif, js,css, adblockkey,fb, gmail, twitter,linkedIn,subscribe,href,http, bracket_2, bracket_3,re_w,new_par, dbslash, bslash,bol_0,bol_1,bol_2,bol_3,bol_4,bol_5,bol_6,bol_7,bol_8,bol_9,bol_10,bol_11,bol_12,bol_13,bol_14,bol_15,bol_16,bol_17,bol_18,bol_19)= (name.strip('('),int(lines),int(spaces),int(words),int(length),int(tabs),int( braces),int( brackets),int(classs),int( javascript),int(meta_content),int( input),int( forum),int( gif),int( js),int(css),int( adblockkey),int(fb),int( gmail),int( twitter),int(linkedIn),int(subscribe),int(href),int(http),int( bracket_2),int( bracket_3),int(re_w),int(new_par),int( dbslash),int( bslash),int(bol_0),int(bol_1),int(bol_2),int(bol_3),int(bol_4),int(bol_5),int(bol_6),int(bol_7),int(bol_8),int(bol_9),int(bol_10),int(bol_11),int(bol_12),int(bol_13),int(bol_14),int(bol_15),int(bol_16),int(bol_17),int(bol_18),int(bol_19.strip(')')))
	if Last__name and Last__name != name:
        	print (Last__name,Last__lines,Last_spaces,Last_words,Last_length,Last_tabs, Last_braces, Last_brackets,Last_classs, Last_javascript,Last_meta_content, Last_input, Last_forum, Last_gif, Last_js,Last_css, Last_adblockkey,Last_fb, Last_gmail, Last_twitter,Last_linkedIn,Last_subscribe,Last_href,Last_http, Last_bracket_2, Last_bracket_3,Last_re_w,Last_new_par, Last_dbslash, Last_bslash,Last_bol_0,Last_bol_1,Last_bol_2,Last_bol_3,Last_bol_4,Last_bol_5,Last_bol_6,Last_bol_7,Last_bol_8,Last_bol_9,Last_bol_10,Last_bol_11,Last_bol_12,Last_bol_13,Last_bol_14,Last_bol_15,Last_bol_16,Last_bol_17,Last_bol_18,Last_bol_19)
        	(Last__name,Last__lines,Last_spaces,Last_words,Last_length,Last_tabs, Last_braces, Last_brackets,Last_classs, Last_javascript,Last_meta_content, Last_input, Last_forum, Last_gif, Last_js,Last_css, Last_adblockkey,Last_fb, Last_gmail, Last_twitter,Last_linkedIn,Last_subscribe,Last_href,Last_http, Last_bracket_2, Last_bracket_3,Last_re_w,Last_new_par, Last_dbslash, Last_bslash,Last_bol_0,Last_bol_1,Last_bol_2,Last_bol_3,Last_bol_4,Last_bol_5,Last_bol_6,Last_bol_7,Last_bol_8,Last_bol_9,Last_bol_10,Last_bol_11,Last_bol_12,Last_bol_13,Last_bol_14,Last_bol_15,Last_bol_16,Last_bol_17,Last_bol_18,Last_bol_19) = (name,int(lines),int(spaces),int(words),int(length),int(tabs),int( braces),int( brackets),int(classs),int( javascript),int(meta_content),int( input),int( forum),int( gif),int( js),int(css),int( adblockkey),int(fb),int( gmail),int( twitter),int(linkedIn),int(subscribe),int(href),int(http),int( bracket_2),int( bracket_3),int(re_w),int(new_par),int( dbslash),int( bslash),int(bol_0),int(bol_1),int(bol_2),int(bol_3),int(bol_4),int(bol_5),int(bol_6),int(bol_7),int(bol_8),int(bol_9),int(bol_10),int(bol_11),int(bol_12),int(bol_13),int(bol_14),int(bol_15),int(bol_16),int(bol_17),int(bol_18),int(bol_19))
	else:
        	(Last__name,Last__lines,Last_spaces,Last_words,Last_length,Last_tabs, Last_braces, Last_brackets,Last_classs, Last_javascript,Last_meta_content, Last_input, Last_forum, Last_gif, Last_js,Last_css, Last_adblockkey,Last_fb, Last_gmail, Last_twitter,Last_linkedIn,Last_subscribe,Last_href,Last_http, Last_bracket_2, Last_bracket_3,Last_re_w,Last_new_par, Last_dbslash, Last_bslash,Last_bol_0,Last_bol_1,Last_bol_2,Last_bol_3,Last_bol_4,Last_bol_5,Last_bol_6,Last_bol_7,Last_bol_8,Last_bol_9,Last_bol_10,Last_bol_11,Last_bol_12,Last_bol_13,Last_bol_14,Last_bol_15,Last_bol_16,Last_bol_17,Last_bol_18,Last_bol_19) = (name,Last__lines+int(lines),Last_spaces+int(spaces),Last_words+int(words),Last_length+int(length),Last_tabs+int(tabs), Last_braces+int(braces), Last_brackets+int(brackets),Last_classs+int(classs), Last_javascript+int(javascript),Last_meta_content+int(meta_content), Last_input+int(input), Last_forum+int(forum), Last_gif+int(gif), Last_js+int(js),Last_css+int(css), Last_adblockkey+int(adblockkey),Last_fb+int(fb), Last_gmail+int(gmail), Last_twitter+int(twitter),Last_linkedIn+int(linkedIn),Last_subscribe+int(subscribe),Last_href+int(href),Last_http+int(http), Last_bracket_2+int(bracket_2), Last_bracket_3+int(bracket_3),Last_re_w+int(re_w),Last_new_par+int(new_par), Last_dbslash+int(dbslash), Last_bslash+int(bslash),Last_bol_0+int(bol_0),Last_bol_1+int(bol_1),Last_bol_2+int(bol_2),Last_bol_3+int(bol_3),Last_bol_4+int(bol_4),Last_bol_5+int(bol_5),Last_bol_6+int(bol_6),Last_bol_7+int(bol_7),Last_bol_8+int(bol_8),Last_bol_9+int(bol_9),Last_bol_10+int(bol_10),Last_bol_11+int(bol_11),Last_bol_12+int(bol_12),Last_bol_13+int(bol_13),Last_bol_14+int(bol_14),Last_bol_15+int(bol_15),Last_bol_16+int(bol_16),Last_bol_17+int(bol_17),Last_bol_18+int(bol_18),Last_bol_19+int(bol_19))
if Last__name:
	print(Last__name,Last__lines,Last_spaces,Last_words,Last_length,Last_tabs, Last_braces, Last_brackets,Last_classs, Last_javascript,Last_meta_content, Last_input, Last_forum, Last_gif, Last_js,Last_css, Last_adblockkey,Last_fb, Last_gmail, Last_twitter,Last_linkedIn,Last_subscribe,Last_href,Last_http, Last_bracket_2, Last_bracket_3,Last_re_w,Last_new_par, Last_dbslash, Last_bslash,Last_bol_0,Last_bol_1,Last_bol_2,Last_bol_3,Last_bol_4,Last_bol_5,Last_bol_6,Last_bol_7,Last_bol_8,Last_bol_9,Last_bol_10,Last_bol_11,Last_bol_12,Last_bol_13,Last_bol_14,Last_bol_15,Last_bol_16,Last_bol_17,Last_bol_18,Last_bol_19)


hadoop jar /usr/lib/hadoop-mapreduce/hadoop-streaming-2.0.0-cdh4.7.0.jar -D mapred.job.name="Getting meta data" \
-files /usr/tmp/mapper.py\
 -input /tmp/dfs/1112409_raw_html.txt \
 -mapper 'python mapper.py'

hadoop jar /usr/lib/hadoop-mapreduce/hadoop-streaming-2.0.0-cdh4.7.0.jar \
 -files /usr/tmp/mapper.py,/usr/tmp/reducer.py \
 -input /tmp/dfs/*.txt \
 -output /tmp/Stream/ \
 -mapper 'python mapper.py' -combiner 'python reducer.py' -reducer 'python reducer.py'